### ISSUE TITLE
Optimization 2: Handle KeyError exceptions that occurs within the Spinner Field

### ISSUE THREAD

**Issue by WinnyTroy** [OpenSRP/xlson#33]
The spinner field is XLSForm's select multiple type. This question type requires the user to include the openmrs_entity_id attribute for all the choices provided within the choice sheet.

survey sheet

type | name | label
-- | -- | --
select multiple moods | user_spinner | What is the mood?

choices sheet

list name | name | label | instance::openmrs_entity_id
-- | -- | -- | --
moods | happy | Happy | 1107AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
moods | sad | Sad | 1713AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
moods | somber | Somber | 2113AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

```JSON
{
      "name": "user_spinner",
      "label": "What is the mood?",
      "type": "select all that apply",
      "children": [
        {
          "name": "happy",
          "label": "Happy",
          "instance": {
            "openmrs_entity_id": "1107AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
          }
        },
        {
          "name": "sad",
          "label": "Sad",
          "instance": {
            "openmrs_entity_id": "1713AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
          }
        },
        {
          "name": "somber",
          "label": "Somber",
          "instance": {
            "openmrs_entity_id": "2113AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
          }
        }
      ]
    }
```

The resulting native form JSON is:

```JSON
{
  "key": "user_spinner",
  "openmrs_entity_parent": "",
  "openmrs_entity": "",
  "openmrs_entity_id": "",
  "type": "spinner",
  "hint": "What is the mood?",
  "values": [
    "Happy",
    "Sad",
    "Somber"
  ],
  "keys": [
    "happy",
    "sad",
    "somber"
  ],
  "openmrs_choice_ids": {
    "happy": "1107AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "sad": "1713AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "somber": "2113AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
  }
}
```

This issue seeks to handle  occurrences when the openmrs_entity_id field is not provided and document the changes presented and their necessity.

**Comment by hngondoki** [comment]
The exception is as below:

(xlson) Onas-MacBook-Pro:xlson ona$ xlson /Users/ona/Downloads/BA-referrals.xlsx 
Traceback (most recent call last):
  File "/Users/ona/.virtualenvs/xlson/bin/xlson", line 11, in <module>
    load_entry_point('xlson==0.0.1', 'console_scripts', 'xlson')()
  File "/Users/ona/.virtualenvs/xlson/lib/python3.7/site-packages/Click-7.0-py3.7.egg/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/ona/.virtualenvs/xlson/lib/python3.7/site-packages/Click-7.0-py3.7.egg/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/ona/.virtualenvs/xlson/lib/python3.7/site-packages/Click-7.0-py3.7.egg/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/ona/.virtualenvs/xlson/lib/python3.7/site-packages/Click-7.0-py3.7.egg/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/ona/.virtualenvs/xlson/lib/python3.7/site-packages/xlson-0.0.1-py3.7.egg/xlson/__init__.py", line 301, in cli
    form = create_native_form(survey.to_json_dict())
  File "/Users/ona/.virtualenvs/xlson/lib/python3.7/site-packages/xlson-0.0.1-py3.7.egg/xlson/__init__.py", line 289, in create_native_form
    data.update(build_field(child))
  File "/Users/ona/.virtualenvs/xlson/lib/python3.7/site-packages/xlson-0.0.1-py3.7.egg/xlson/__init__.py", line 260, in build_field
    field = {options[NAME]: Step(**options)}
  File "/Users/ona/.virtualenvs/xlson/lib/python3.7/site-packages/xlson-0.0.1-py3.7.egg/xlson/__init__.py", line 247, in __init__
    for child in kwargs[CHILDREN]
  File "/Users/ona/.virtualenvs/xlson/lib/python3.7/site-packages/xlson-0.0.1-py3.7.egg/xlson/__init__.py", line 248, in <listcomp>
    if child.get(TYPE) in SUPPORTED_QUESTIONS_TYPES
  File "/Users/ona/.virtualenvs/xlson/lib/python3.7/site-packages/xlson-0.0.1-py3.7.egg/xlson/__init__.py", line 272, in build_field
    field = SpinnerField(**options)
  File "/Users/ona/.virtualenvs/xlson/lib/python3.7/site-packages/xlson-0.0.1-py3.7.egg/xlson/__init__.py", line 228, in __init__
    child["instance"]["openmrs_entity_id"] for child in params[CHILDREN]
  File "/Users/ona/.virtualenvs/xlson/lib/python3.7/site-packages/xlson-0.0.1-py3.7.egg/xlson/__init__.py", line 228, in <listcomp>
    child["instance"]["openmrs_entity_id"] for child in params[CHILDREN]
KeyError: 'instance'
